### ISSUE TITLE
Don't both with @author annotations in comments

### ISSUE THREAD

**Issue by humphd** [LuigiZaccagnini/octo#6]
For example: https://github.com/LuigiZaccagnini/octo/blob/main/bin/fileFunctions.js#L30.

I would leave these out.  Your license + git commit info includes this information, and it will drift out of date, as people write PRs against your repo.

**Comment by LuigiZaccagnini** [comment]
Closed by https://github.com/LuigiZaccagnini/octo/commit/2875fa8aa9a5abb3820529d7d962ab005a98ebcc
