### ISSUE TITLE
Markdown for static site generator - issue-6

### ISSUE THREAD

**Issue by nguyenhung15913** [LuigiZaccagnini/octo#7]
Hi Luigi, I am interested in your project and I would like to add support for Markdown in it.
In more detail, I will fork, clone then modify the code so that it will support both .txt and .md files. If users input .txt file, nothing will change. However, if .md is input, at least one aspect of Markdown into HTML will be parsed.
If you are good with my request. Please reply to this post thanks.

**Comment by LuigiZaccagnini** [comment]
Sounds good @nguyenhung15913 ! Glad to see your interest in my project , thank you!
